
'''
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
def calculate_sum(n):
    if n <= 0:
        return 0

    fibo = [0] * (n + 1)
    print(fibo)
    fibo[1] = 1

    # Initialize result
    sm = fibo[0] + fibo[1]

    # Add remaining terms
    for i in range(2, n + 1):
        fibo[i] = fibo[i - 1] + fibo[i - 2]
        sm = sm + fibo[i]
    print(fibo)
    return sm


# Driver program to test
# above function
n = 4
print("Sum of Fibonacci numbers is : ", calculate_sum(n))
